baseURL = 'https://trust2065.github.io/blog/'
languageCode = 'zh-tw'
title = 'æ¾³æ´²0-3æ­²è‚²å…’æŒ‡å—'
theme = "PaperMod"

hasCJKLanguage = true
summaryLength = 50
enableGitInfo = true

[frontmatter]
    date = ["date", ":filename", ":git", "publishDate"]
    lastmod = ["lastmod", ":git", "date", "publishDate"]
    publishDate = ["publishDate", ":filename", ":git", "date"]

[outputs]
    home = ["HTML", "RSS", "JSON"]

[params]
    env = "production"
    title = "æ¾³æ´²0-3æ­²è‚²å…’æŒ‡å—"
    description = "åˆ†äº«æ¾³æ´²è‚²å…’ç¶“é©—å’Œå»ºè­°"
    author = "Chocoli"
    
    # æ ¸å¿ƒå¤–è§€è¨­å®š
    defaultTheme = "auto" # dark, light, auto
    disableThemeToggle = false
    ShowReadingTime = true
    ShowShareButtons = false
    ShowPostNavLinks = true
    ShowBreadCrumbs = true
    ShowCodeCopyButtons = true
    
    # é¦–é è³‡è¨Š
    [params.homeInfoParams]
        Title = "ğŸ‡¦ğŸ‡º æ¾³æ´²0-3æ­²è‚²å…’æŒ‡å—"
        Content = "é€™è£¡æ˜¯åˆ†äº«æ¾³æ´²è‚²å…’ç¶“é©—ã€å¯¦ç”¨è³‡è¨Šèˆ‡ç”Ÿæ´»é»æ»´çš„ç©ºé–“ã€‚å¸Œæœ›é€™äº›å…§å®¹èƒ½é™ªä¼´æ‚¨èˆ‡å¯¶å¯¶ä¸€èµ·æˆé•·ã€‚"

    [params.assets]
        disableHLJS = false

[menu]
    [[menu.main]]
        identifier = "search"
        name = "æœå°‹"
        url = "/search/"
        weight = 5
    [[menu.main]]
        identifier = "home"
        name = "é¦–é "
        url = "/"
        weight = 10
    [[menu.main]]
        identifier = "posts"
        name = "æ–‡ç« åˆ—è¡¨"
        url = "/posts/"
        weight = 20
    [[menu.main]]
        identifier = "categories"
        name = "åˆ†é¡"
        url = "/categories/"
        weight = 30
    [[menu.main]]
        identifier = "tags"
        name = "æ¨™ç±¤"
        url = "/tags/"
        weight = 40


[taxonomies]
    category = "categories"
    tag = "tags"
    series = "series"

[markup.goldmark.renderer]
    unsafe = true
